# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  java-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v1
      with:
         #gradle-version: 6.5
         gradle-version: 5.6

  publish-docker:
    runs-on: ubuntu-latest
    needs: ['java-build']
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: peterjakubik/${{ secrets.TAG_NAME }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
  container-scan:
    runs-on: ubuntu-latest
    needs: ['publish-docker']
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Anchore Container Scan
      uses: anchore/scan-action@main
      with:
         image: peterjakubik/${{ secrets.TAG_NAME }}
         acs-report-enable: true
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
  
